### PR TITLE
Allow SAMLResponses in query params to be processed

### PR DESCRIPTION
**Pull request by edpaget**
The SAML IdP I'm working with responds to HTTP-Redirect bindings by redirecting back to my callback with the SAMLResponse as a query parameters. This updates handling that response by allowing it to either be in a POST body or deflated and encoded in a query param.

### CODE REVIEW

**Comment by gkwang** [comment]
According the the SAML spec, HTTP-Redirect binding isn't supported for Web SSO, so I'm not sure if adding support to it is a good idea.
https://docs.oasis-open.org/security/saml/v2.0/saml-conformance-2.0-os.pdf#158
Additionally, some SAML Responses (for SSO, not SLO) can contain a lot of claims, which can exceed the url length restrictions and cause issues.

**Comment by edpaget** [comment]
The SAML provider I have to work with claims that their behaviour is allowed by the spec. I tried to persuade them that it was not, but was unable to have it changed. I'm not sure if that's a common thing with other providers or not. 

Would you consider accepting this change behind a configuration parameter that has to be explicitly enabled?

**Comment by gkwang** [comment]
@machuga what do you think?

**Comment by machuga** [comment]
I'm reluctant to add any new configurable options that support features of improper implementations. Are there alternate solutions that we can consider for this type of issue?

**Pull request closed without merging**
