### PR TITLE
 Replace x509 library with node-forge

### PR DESCRIPTION
**Pull request by edpaget**
x509 seems to be relatively inactive and does not fully work on node 8 or above,
failing entirely to compile on node 10. node-forge seems to provide the same
features this library was using x509 for and seems to have much wider usage
according npm's stats.

### CODE REVIEW

**Comment by machuga** [comment]
Excellent, thanks! We'll investigate.

**Comment by ntfs32** [comment]
What's the news?

**Comment by t83714** [comment]
Any updates on this? 👀

**Comment by apalumbo** [comment]
@machuga as we really need this PR to use this lib with an updated node version , there is something that we could do to speedup the merge?

**Comment by machuga** [comment]
@apalumbo Hello! I've pinged the responsible team for review.

**Comment by jeremywallace-hlg** [comment]
What is the ETA on this? I have a previous version using x509 that was working but I am unable to get it installed after company upgraded OS to Windows 10. Is this likely to fix the x509 issue and allow it to work correctly?

**Comment by lysektomas** [comment]
Any update on this? x509 cant be rebuild in win10/linux.. please just merge it - last working version is 3.0.13

**Comment by lysektomas** [comment]
@glena - please review those few lines, thank you

**Pull request closed without merging**
