### PR TITLE
add license to package.json

### PR DESCRIPTION
**Pull request by anotheredward**

### CODE REVIEW

**Comment by siacomuzzi** [comment]
thanks!

**Comment by siacomuzzi** [comment]
Sorry, but we already have `"licenses"`: https://github.com/auth0/passport-wsfed-saml2/blob/master/package.json#L51-L56

**Comment by anotheredward** [comment]
Hi, Thanks for your reply.

I created this commit to ease automated tooling when trying to extract licenses from lots of bower packages. There isn't any guarantee that a bower package has a package.json file, although a lot of them do.

Also note that the "licences" key in the package.json is deprecated: https://docs.npmjs.com/files/package.json .
Your license key would look like:  `"license": "MIT",` in the new format.

Happy to close PR if you still don't wish to add a license key to your bower.json file though!

**Comment by siacomuzzi** [comment]
thanks for the details. Could you please replace include "license" and remove "licenses"?

**Comment by anotheredward** [comment]
Ok, Will do that in a different PR.

**Pull request merged**
